apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-deploy
  name: my-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
